//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.Blog = new HashSet<Blog>();
            this.Comment = new HashSet<Comment>();
            this.CommentActivity = new HashSet<CommentActivity>();
            this.FavoriteRoute = new HashSet<FavoriteRoute>();
            this.Friend = new HashSet<Friend>();
            this.Friend1 = new HashSet<Friend>();
            this.Mailbox = new HashSet<Mailbox>();
            this.Mailbox1 = new HashSet<Mailbox>();
            this.Post = new HashSet<Post>();
            this.PostUsers = new HashSet<PostUsers>();
            this.Profile = new HashSet<Profile>();
            this.Route = new HashSet<Route>();
            this.RouteRating = new HashSet<RouteRating>();
            this.Trip = new HashSet<Trip>();
            this.TripBuget = new HashSet<TripBuget>();
            this.TripEquipment = new HashSet<TripEquipment>();
            this.UserEquipment = new HashSet<UserEquipment>();
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<Blog> Blog { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<CommentActivity> CommentActivity { get; set; }
        public virtual ICollection<FavoriteRoute> FavoriteRoute { get; set; }
        public virtual ICollection<Friend> Friend { get; set; }
        public virtual ICollection<Friend> Friend1 { get; set; }
        public virtual ICollection<Mailbox> Mailbox { get; set; }
        public virtual ICollection<Mailbox> Mailbox1 { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<PostUsers> PostUsers { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<Route> Route { get; set; }
        public virtual ICollection<RouteRating> RouteRating { get; set; }
        public virtual ICollection<Trip> Trip { get; set; }
        public virtual ICollection<TripBuget> TripBuget { get; set; }
        public virtual ICollection<TripEquipment> TripEquipment { get; set; }
        public virtual ICollection<UserEquipment> UserEquipment { get; set; }
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
