//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
            this.CommentActivity = new HashSet<CommentActivity>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public long PostID { get; set; }
        public string CommentText { get; set; }
        public Nullable<long> CommentID { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual Post Post { get; set; }
        public virtual ICollection<CommentActivity> CommentActivity { get; set; }
    }
}
