//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.PostCountry = new HashSet<PostCountry>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<PostCountry> PostCountry { get; set; }
    }
}
