//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikeGroundEntities : DbContext
    {
        public BikeGroundEntities()
            : base("name=BikeGroundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CommentActivity> CommentActivity { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentCategory> EquipmentCategory { get; set; }
        public virtual DbSet<FavoriteRoute> FavoriteRoute { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Mailbox> Mailbox { get; set; }
        public virtual DbSet<MailType> MailType { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostCountry> PostCountry { get; set; }
        public virtual DbSet<PostUsers> PostUsers { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<ProfileActivity> ProfileActivity { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<RefreshTokens> RefreshTokens { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<RouteRating> RouteRating { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<TripBuget> TripBuget { get; set; }
        public virtual DbSet<TripEquipment> TripEquipment { get; set; }
        public virtual DbSet<UserEquipment> UserEquipment { get; set; }
        public virtual DbSet<Wall> Wall { get; set; }
    }
}
