//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailbox
    {
        public long ID { get; set; }
        public string FromID { get; set; }
        public string ToID { get; set; }
        public int MailTypeID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsRead { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual MailType MailType { get; set; }
    }
}
