//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailType
    {
        public MailType()
        {
            this.Mailbox = new HashSet<Mailbox>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Mailbox> Mailbox { get; set; }
    }
}
