//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comment = new HashSet<Comment>();
            this.PostCountry = new HashSet<PostCountry>();
            this.PostUsers = new HashSet<PostUsers>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public long TripID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string MapRoute { get; set; }
        public string LastLocation { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual ICollection<PostCountry> PostCountry { get; set; }
        public virtual ICollection<PostUsers> PostUsers { get; set; }
    }
}
