//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecundaryEMail { get; set; }
        public string About { get; set; }
        public Nullable<int> ProfileActivityID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ProfileActivity ProfileActivity { get; set; }
    }
}
