//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileActivity
    {
        public ProfileActivity()
        {
            this.CommentActivity = new HashSet<CommentActivity>();
            this.Friend = new HashSet<Friend>();
            this.Profile = new HashSet<Profile>();
        }
    
        public int ID { get; set; }
        public string ActivityType { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CommentActivity> CommentActivity { get; set; }
        public virtual ICollection<Friend> Friend { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
    }
}
