//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.FavoriteRoute = new HashSet<FavoriteRoute>();
            this.RouteRating = new HashSet<RouteRating>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Lenght { get; set; }
        public decimal ElevationUp { get; set; }
        public decimal ElevationDown { get; set; }
        public string GeoJson { get; set; }
        public string GpxURL { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool Official { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<FavoriteRoute> FavoriteRoute { get; set; }
        public virtual ICollection<RouteRating> RouteRating { get; set; }
    }
}
