//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripBuget
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public long TripID { get; set; }
        public Nullable<long> PostID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
