//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Tester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Post = new HashSet<Post>();
            this.TripBuget = new HashSet<TripBuget>();
            this.TripEquipment = new HashSet<TripEquipment>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public long BlogID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public decimal Distance { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Blog Blog { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<TripBuget> TripBuget { get; set; }
        public virtual ICollection<TripEquipment> TripEquipment { get; set; }
    }
}
