//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AspNetUsers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AspNetUsers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeGround.Models.Resources.AspNetUsers", typeof(AspNetUsers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id .
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IdRequired is required.
        /// </summary>
        public static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserName .
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserNameRequired is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserNameLong has invalid lenght.
        /// </summary>
        public static string UserNameLong {
            get {
                return ResourceManager.GetString("UserNameLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailRequired is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailLong has invalid lenght.
        /// </summary>
        public static string EmailLong {
            get {
                return ResourceManager.GetString("EmailLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailConfirmed .
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailConfirmedRequired is required.
        /// </summary>
        public static string EmailConfirmedRequired {
            get {
                return ResourceManager.GetString("EmailConfirmedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PasswordHash .
        /// </summary>
        public static string PasswordHash {
            get {
                return ResourceManager.GetString("PasswordHash", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PasswordHashRequired is required.
        /// </summary>
        public static string PasswordHashRequired {
            get {
                return ResourceManager.GetString("PasswordHashRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PasswordHashLong has invalid lenght.
        /// </summary>
        public static string PasswordHashLong {
            get {
                return ResourceManager.GetString("PasswordHashLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecurityStamp .
        /// </summary>
        public static string SecurityStamp {
            get {
                return ResourceManager.GetString("SecurityStamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecurityStampRequired is required.
        /// </summary>
        public static string SecurityStampRequired {
            get {
                return ResourceManager.GetString("SecurityStampRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecurityStampLong has invalid lenght.
        /// </summary>
        public static string SecurityStampLong {
            get {
                return ResourceManager.GetString("SecurityStampLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber .
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberRequired is required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberLong has invalid lenght.
        /// </summary>
        public static string PhoneNumberLong {
            get {
                return ResourceManager.GetString("PhoneNumberLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberConfirmed .
        /// </summary>
        public static string PhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberConfirmedRequired is required.
        /// </summary>
        public static string PhoneNumberConfirmedRequired {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TwoFactorEnabled .
        /// </summary>
        public static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TwoFactorEnabledRequired is required.
        /// </summary>
        public static string TwoFactorEnabledRequired {
            get {
                return ResourceManager.GetString("TwoFactorEnabledRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LockoutEndDateUtc .
        /// </summary>
        public static string LockoutEndDateUtc {
            get {
                return ResourceManager.GetString("LockoutEndDateUtc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LockoutEndDateUtcRequired is required.
        /// </summary>
        public static string LockoutEndDateUtcRequired {
            get {
                return ResourceManager.GetString("LockoutEndDateUtcRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LockoutEnabled .
        /// </summary>
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LockoutEnabledRequired is required.
        /// </summary>
        public static string LockoutEnabledRequired {
            get {
                return ResourceManager.GetString("LockoutEnabledRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccessFailedCount .
        /// </summary>
        public static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccessFailedCountRequired is required.
        /// </summary>
        public static string AccessFailedCountRequired {
            get {
                return ResourceManager.GetString("AccessFailedCountRequired", resourceCulture);
            }
        }

    }
}