//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Friend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Friend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeGround.Models.Resources.Friend", typeof(Friend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID .
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserIDRequired is required.
        /// </summary>
        public static string UserIDRequired {
            get {
                return ResourceManager.GetString("UserIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FriendID .
        /// </summary>
        public static string FriendID {
            get {
                return ResourceManager.GetString("FriendID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FriendIDRequired is required.
        /// </summary>
        public static string FriendIDRequired {
            get {
                return ResourceManager.GetString("FriendIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProfileActivityID .
        /// </summary>
        public static string ProfileActivityID {
            get {
                return ResourceManager.GetString("ProfileActivityID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProfileActivityIDRequired is required.
        /// </summary>
        public static string ProfileActivityIDRequired {
            get {
                return ResourceManager.GetString("ProfileActivityIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active .
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ActiveRequired is required.
        /// </summary>
        public static string ActiveRequired {
            get {
                return ResourceManager.GetString("ActiveRequired", resourceCulture);
            }
        }

    }
}