//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mailbox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mailbox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeGround.Models.Resources.Mailbox", typeof(Mailbox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IDRequired is required.
        /// </summary>
        public static string IDRequired {
            get {
                return ResourceManager.GetString("IDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FromID .
        /// </summary>
        public static string FromID {
            get {
                return ResourceManager.GetString("FromID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FromIDRequired is required.
        /// </summary>
        public static string FromIDRequired {
            get {
                return ResourceManager.GetString("FromIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ToID .
        /// </summary>
        public static string ToID {
            get {
                return ResourceManager.GetString("ToID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ToIDRequired is required.
        /// </summary>
        public static string ToIDRequired {
            get {
                return ResourceManager.GetString("ToIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MailTypeID .
        /// </summary>
        public static string MailTypeID {
            get {
                return ResourceManager.GetString("MailTypeID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MailTypeIDRequired is required.
        /// </summary>
        public static string MailTypeIDRequired {
            get {
                return ResourceManager.GetString("MailTypeIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subject .
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubjectRequired is required.
        /// </summary>
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubjectLong has invalid lenght.
        /// </summary>
        public static string SubjectLong {
            get {
                return ResourceManager.GetString("SubjectLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Body .
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BodyRequired is required.
        /// </summary>
        public static string BodyRequired {
            get {
                return ResourceManager.GetString("BodyRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BodyLong has invalid lenght.
        /// </summary>
        public static string BodyLong {
            get {
                return ResourceManager.GetString("BodyLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateAdded .
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateAddedRequired is required.
        /// </summary>
        public static string DateAddedRequired {
            get {
                return ResourceManager.GetString("DateAddedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IsRead .
        /// </summary>
        public static string IsRead {
            get {
                return ResourceManager.GetString("IsRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IsReadRequired is required.
        /// </summary>
        public static string IsReadRequired {
            get {
                return ResourceManager.GetString("IsReadRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active .
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ActiveRequired is required.
        /// </summary>
        public static string ActiveRequired {
            get {
                return ResourceManager.GetString("ActiveRequired", resourceCulture);
            }
        }

    }
}