//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeGround.Models.Resources.Notification", typeof(Notification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IDRequired is required.
        /// </summary>
        public static string IDRequired {
            get {
                return ResourceManager.GetString("IDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ToUserID .
        /// </summary>
        public static string ToUserID {
            get {
                return ResourceManager.GetString("ToUserID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ToUserIDRequired is required.
        /// </summary>
        public static string ToUserIDRequired {
            get {
                return ResourceManager.GetString("ToUserIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message .
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MessageRequired is required.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MessageLong has invalid lenght.
        /// </summary>
        public static string MessageLong {
            get {
                return ResourceManager.GetString("MessageLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigation .
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NavigationRequired is required.
        /// </summary>
        public static string NavigationRequired {
            get {
                return ResourceManager.GetString("NavigationRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NavigationLong has invalid lenght.
        /// </summary>
        public static string NavigationLong {
            get {
                return ResourceManager.GetString("NavigationLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unread .
        /// </summary>
        public static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UnreadRequired is required.
        /// </summary>
        public static string UnreadRequired {
            get {
                return ResourceManager.GetString("UnreadRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotificationTypeID .
        /// </summary>
        public static string NotificationTypeID {
            get {
                return ResourceManager.GetString("NotificationTypeID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotificationTypeIDRequired is required.
        /// </summary>
        public static string NotificationTypeIDRequired {
            get {
                return ResourceManager.GetString("NotificationTypeIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotificationVersionID .
        /// </summary>
        public static string NotificationVersionID {
            get {
                return ResourceManager.GetString("NotificationVersionID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotificationVersionIDRequired is required.
        /// </summary>
        public static string NotificationVersionIDRequired {
            get {
                return ResourceManager.GetString("NotificationVersionIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotificationVersionIDLong has invalid lenght.
        /// </summary>
        public static string NotificationVersionIDLong {
            get {
                return ResourceManager.GetString("NotificationVersionIDLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateAdded .
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateAddedRequired is required.
        /// </summary>
        public static string DateAddedRequired {
            get {
                return ResourceManager.GetString("DateAddedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active .
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ActiveRequired is required.
        /// </summary>
        public static string ActiveRequired {
            get {
                return ResourceManager.GetString("ActiveRequired", resourceCulture);
            }
        }

    }
}