//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeGround.Models.Resources.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis je predugačak.
        /// </summary>
        public static string AboutLong {
            get {
                return ResourceManager.GetString("AboutLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis je obavezno polje.
        /// </summary>
        public static string AboutRequired {
            get {
                return ResourceManager.GetString("AboutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kratki opis smještaja.
        /// </summary>
        public static string AccDescription {
            get {
                return ResourceManager.GetString("AccDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis smještaja je predugačak.
        /// </summary>
        public static string AccDescriptionLong {
            get {
                return ResourceManager.GetString("AccDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudite smještaj.
        /// </summary>
        public static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smještaj je obavezno polje.
        /// </summary>
        public static string AccommodationRequired {
            get {
                return ResourceManager.GetString("AccommodationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čavrljanje.
        /// </summary>
        public static string ChatActivity {
            get {
                return ResourceManager.GetString("ChatActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čavrljanje je obavezno polje.
        /// </summary>
        public static string ChatActivityRequired {
            get {
                return ResourceManager.GetString("ChatActivityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv grada je predugačak.
        /// </summary>
        public static string CityLong {
            get {
                return ResourceManager.GetString("CityLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad je obavezno polje.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država je obavezno polje.
        /// </summary>
        public static string CountryIDRequired {
            get {
                return ResourceManager.GetString("CountryIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upisano ime je predugačko.
        /// </summary>
        public static string FirstNameLong {
            get {
                return ResourceManager.GetString("FirstNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno polje.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDRequired.
        /// </summary>
        public static string IDRequired {
            get {
                return ResourceManager.GetString("IDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upisano prezime je predugačko.
        /// </summary>
        public static string LastNameLong {
            get {
                return ResourceManager.GetString("LastNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivnost profila.
        /// </summary>
        public static string ProfileActivityID {
            get {
                return ResourceManager.GetString("ProfileActivityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivnost profila je obavezno polje.
        /// </summary>
        public static string ProfileActivityIDRequired {
            get {
                return ResourceManager.GetString("ProfileActivityIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatni e-mail.
        /// </summary>
        public static string SecundaryEMail {
            get {
                return ResourceManager.GetString("SecundaryEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upisan e-mail je predugačak.
        /// </summary>
        public static string SecundaryEMailLong {
            get {
                return ResourceManager.GetString("SecundaryEMailLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatni e-mail je obavezno polje.
        /// </summary>
        public static string SecundaryEMailRequired {
            get {
                return ResourceManager.GetString("SecundaryEMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIDRequired.
        /// </summary>
        public static string UserIDRequired {
            get {
                return ResourceManager.GetString("UserIDRequired", resourceCulture);
            }
        }
    }
}
