//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeGround.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Route {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Route() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeGround.Models.Resources.Route", typeof(Route).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID .
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IDRequired is required.
        /// </summary>
        public static string IDRequired {
            get {
                return ResourceManager.GetString("IDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserID .
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserIDRequired is required.
        /// </summary>
        public static string UserIDRequired {
            get {
                return ResourceManager.GetString("UserIDRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NameRequired is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NameLong has invalid lenght.
        /// </summary>
        public static string NameLong {
            get {
                return ResourceManager.GetString("NameLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DescriptionRequired is required.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DescriptionLong has invalid lenght.
        /// </summary>
        public static string DescriptionLong {
            get {
                return ResourceManager.GetString("DescriptionLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lenght .
        /// </summary>
        public static string Lenght {
            get {
                return ResourceManager.GetString("Lenght", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LenghtRequired is required.
        /// </summary>
        public static string LenghtRequired {
            get {
                return ResourceManager.GetString("LenghtRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ElevationUp .
        /// </summary>
        public static string ElevationUp {
            get {
                return ResourceManager.GetString("ElevationUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ElevationUpRequired is required.
        /// </summary>
        public static string ElevationUpRequired {
            get {
                return ResourceManager.GetString("ElevationUpRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ElevationDown .
        /// </summary>
        public static string ElevationDown {
            get {
                return ResourceManager.GetString("ElevationDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ElevationDownRequired is required.
        /// </summary>
        public static string ElevationDownRequired {
            get {
                return ResourceManager.GetString("ElevationDownRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GeoJson .
        /// </summary>
        public static string GeoJson {
            get {
                return ResourceManager.GetString("GeoJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GeoJsonRequired is required.
        /// </summary>
        public static string GeoJsonRequired {
            get {
                return ResourceManager.GetString("GeoJsonRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GeoJsonLong has invalid lenght.
        /// </summary>
        public static string GeoJsonLong {
            get {
                return ResourceManager.GetString("GeoJsonLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GpxURL .
        /// </summary>
        public static string GpxURL {
            get {
                return ResourceManager.GetString("GpxURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GpxURLRequired is required.
        /// </summary>
        public static string GpxURLRequired {
            get {
                return ResourceManager.GetString("GpxURLRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GpxURLLong has invalid lenght.
        /// </summary>
        public static string GpxURLLong {
            get {
                return ResourceManager.GetString("GpxURLLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateAdded .
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DateAddedRequired is required.
        /// </summary>
        public static string DateAddedRequired {
            get {
                return ResourceManager.GetString("DateAddedRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Official .
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OfficialRequired is required.
        /// </summary>
        public static string OfficialRequired {
            get {
                return ResourceManager.GetString("OfficialRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active .
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ActiveRequired is required.
        /// </summary>
        public static string ActiveRequired {
            get {
                return ResourceManager.GetString("ActiveRequired", resourceCulture);
            }
        }

    }
}